/**
 * What needs work — the contribution queue.
 *
 * Every record that is a `candidate` is a known gap, not a mistake. This turns
 * those gaps into a ranked list a person can actually pick up: which field is
 * missing, on how many records, for which brands.
 *
 * An open dataset that looks finished gets no contributions. This page is how
 * the gaps stay visible.
 *
 *   npm run gaps            print the report
 *   npm run gaps -- --write update NEEDS-WORK.md
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  ROOT, loadDomainSchemas, productFiles, readRecords,
  type ProductRecord,
} from "./schema.ts";

interface Gap { domain: string; category: string; field: string; count: number; brands: Map<string, number> }

function collect() {
  const schemas = loadDomainSchemas();
  const gaps = new Map<string, Gap>();
  const totals = new Map<string, { entries: number; candidates: number }>();
  const noIngredients = new Map<string, number>();
  const noGtin = new Map<string, number>();

  for (const file of productFiles()) {
    for (const item of readRecords(file)) {
      if (!("record" in item)) continue;
      const r: ProductRecord = item.record;
      const t = totals.get(r.domain) ?? { entries: 0, candidates: 0 };
      if ((r.status ?? "entry") === "candidate") t.candidates++; else t.entries++;
      totals.set(r.domain, t);

      if (!r.ingredients?.length && ["beauty", "grocery"].includes(r.domain))
        noIngredients.set(r.domain, (noIngredients.get(r.domain) ?? 0) + 1);
      // funds, cards and deposits have no barcode by nature — that is not a gap
      const PHYSICAL = ["beauty", "grocery", "appliances", "phones", "printers", "networking"];
      if (!r.identifiers?.gtin && PHYSICAL.includes(r.domain))
        noGtin.set(r.domain, (noGtin.get(r.domain) ?? 0) + 1);

      if ((r.status ?? "entry") !== "candidate") continue;
      const ds = schemas.get(r.domain);
      const cs = ds?.categories[r.category] ?? ds?.categories["_default"];
      for (const field of cs?.required ?? []) {
        const v = r.attributes?.[field];
        if (v !== undefined && v !== null && v !== "" && !(Array.isArray(v) && !v.length)) continue;
        const key = `${r.domain}|${r.category}|${field}`;
        const g = gaps.get(key) ?? { domain: r.domain, category: r.category, field, count: 0, brands: new Map() };
        g.count++;
        g.brands.set(r.brand, (g.brands.get(r.brand) ?? 0) + 1);
        gaps.set(key, g);
      }
    }
  }
  return { gaps: [...gaps.values()].sort((a, b) => b.count - a.count), totals, noIngredients, noGtin };
}

function render(): string {
  const { gaps, totals, noIngredients, noGtin } = collect();
  const L: string[] = [];
  const n = (x: number) => x.toLocaleString("en-IN");

  L.push("# What needs work", "");
  L.push("Every line here is a **known gap**, not a mistake. A record marked `candidate`");
  L.push("is one we published honestly without a fact we could not verify — because a");
  L.push("missing field is a task, and a wrong field is a broken promise.", "");
  L.push("Pick anything below. Most of it needs a person with the pack, the product page");
  L.push("or the document in front of them — not code.", "");
  L.push("_Generated by `npm run gaps`. Do not edit by hand._", "");

  L.push("## Where the catalogue stands", "");
  L.push("| Domain | Complete | Needs work | Total |");
  L.push("|---|---:|---:|---:|");
  let te = 0, tc = 0;
  for (const [dom, t] of [...totals].sort((a, b) => (b[1].entries + b[1].candidates) - (a[1].entries + a[1].candidates))) {
    te += t.entries; tc += t.candidates;
    L.push(`| ${dom} | ${n(t.entries)} | ${n(t.candidates)} | ${n(t.entries + t.candidates)} |`);
  }
  L.push(`| **all** | **${n(te)}** | **${n(tc)}** | **${n(te + tc)}** |`, "");

  L.push("## Missing facts, most common first", "");
  L.push("| Domain | Category | Missing field | Records | Brands most affected |");
  L.push("|---|---|---|---:|---|");
  for (const g of gaps.slice(0, 30)) {
    const top = [...g.brands].sort((a, b) => b[1] - a[1]).slice(0, 3)
      .map(([b, c]) => `${b} (${c})`).join(", ");
    L.push(`| ${g.domain} | ${g.category} | \`${g.field}\` | ${n(g.count)} | ${top} |`);
  }
  if (gaps.length > 30) L.push(`\n_…and ${gaps.length - 30} more field/category combinations._`);
  L.push("");

  L.push("## The two gaps worth most", "");
  L.push("**Ingredient lists.** The fact people trust most, and the one brands publish as an");
  L.push("image so nobody can search it. Typing one off a pack, in declared order, is the");
  L.push("single most valuable contribution to this dataset.", "");
  L.push("| Domain | Records with no ingredient list |");
  L.push("|---|---:|");
  for (const [d, c] of [...noIngredients].sort((a, b) => b[1] - a[1])) L.push(`| ${d} | ${n(c)} |`);
  L.push("");
  L.push("**Barcodes.** A GTIN is how a record matches a listing on any shop. Without one,");
  L.push("a product can only be matched by name, which is guesswork.", "");
  L.push("| Domain | Records with no GTIN |");
  L.push("|---|---:|");
  for (const [d, c] of [...noGtin].sort((a, b) => b[1] - a[1]).slice(0, 8)) L.push(`| ${d} | ${n(c)} |`);
  L.push("");

  L.push("## How to fill one in", "");
  L.push("1. Find the record: `grep -rn \"<product name>\" products/`");
  L.push("2. Add the field to `attributes`, and a source with today's date saying where you read it");
  L.push("3. If the category's required fields are now all present, change `\"status\"` to `\"entry\"`");
  L.push("4. `npm run format && npm run validate`, then open a pull request", "");
  L.push("Never guess. If the pack is unreadable or the PDF cell is merged, leave it — a gap");
  L.push("is a task for the next person, and a wrong number is worse than no number.");
  return L.join("\n") + "\n";
}

const out = render();
if (process.argv.includes("--write")) {
  writeFileSync(join(ROOT, "NEEDS-WORK.md"), out);
  console.log("wrote NEEDS-WORK.md");
} else {
  console.log(out);
}
